//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllianceCandidate
    {
        public System.Guid UserGuid { get; set; }
        public int AllianceId { get; set; }
        public bool Applicant { get; set; }
        public bool Invite { get; set; }
        public Nullable<byte> UniverseId { get; set; }
    }
}
