//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfData
{
    using System;
    using System.Collections.Generic;

    using global::System;

	public partial class Alliance
    {
        public int Id { get; set; }
        public string Shortname { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<byte> UniverseId { get; set; }
        public Nullable<bool> IsExtreme { get; set; }
        public Nullable<System.DateTime> Added { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    
        public virtual Universe Universe { get; set; }
    }
}
