//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CombatUnit
    {
        public byte CombatUnitId { get; set; }
        public string Name { get; set; }
        public byte BattleCalcField { get; set; }
        public bool MakesDebris { get; set; }
        public int BaseSpeed { get; set; }
        public Nullable<short> BaseSpeed2 { get; set; }
        public int Ore { get; set; }
        public int Crystal { get; set; }
        public int Hydrogen { get; set; }
        public int BaseAttack { get; set; }
        public int BaseShield { get; set; }
        public int BaseHull { get; set; }
        public int CargoCapacity { get; set; }
        public int FuelConsumption { get; set; }
        public Nullable<int> FuelConsumption2 { get; set; }
    }
}
