//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Espionage
    {
        public int EspionageId { get; set; }
        public Nullable<byte> ShipYard { get; set; }
        public Nullable<byte> Capitol { get; set; }
        public Nullable<byte> ResearchLab { get; set; }
        public Nullable<byte> MissileSilo { get; set; }
        public Nullable<byte> Factory { get; set; }
        public Nullable<byte> OreWarehouse { get; set; }
        public Nullable<byte> CrystalWarehouse { get; set; }
        public Nullable<byte> HydrogenStorage { get; set; }
        public Nullable<byte> Foundry { get; set; }
        public Nullable<byte> OreMine { get; set; }
        public Nullable<byte> CrystalMine { get; set; }
        public Nullable<byte> HydrogenSynthesizer { get; set; }
        public Nullable<byte> LaserTech { get; set; }
        public Nullable<byte> ArmorTech { get; set; }
        public Nullable<byte> WeaponsTech { get; set; }
        public Nullable<byte> ShieldTech { get; set; }
        public Nullable<byte> ParticleTech { get; set; }
        public Nullable<byte> JetDrive { get; set; }
        public Nullable<byte> AiTech { get; set; }
        public Nullable<byte> EnergyTech { get; set; }
        public Nullable<byte> EspionageTech { get; set; }
        public Nullable<byte> PulseDrive { get; set; }
        public Nullable<byte> PlasmaTech { get; set; }
        public Nullable<byte> FtlTech { get; set; }
        public Nullable<byte> ExpeditionTech { get; set; }
        public Nullable<byte> WarpDrive { get; set; }
        public Nullable<byte> ARCN { get; set; }
        public Nullable<byte> ABMissile { get; set; }
        public Nullable<byte> IBMissile { get; set; }
        public Nullable<int> TechsId { get; set; }
        public Nullable<int> BuildingsId { get; set; }
    
        public virtual EspionageBuilding EspionageBuilding { get; set; }
    }
}
