//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExplorerUser
    {
        public int Id { get; set; }
        public System.Guid UserGuid { get; set; }
        public System.Guid Token { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<int> AllianceId { get; set; }
        public bool IsOfficer { get; set; }
        public Nullable<int> XPlayerId { get; set; }
        public Nullable<int> XAllianceId { get; set; }
        public bool XIsOfficer { get; set; }
    }
}
