//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExplorerUser_Player
    {
        public int ExplorerUserId { get; set; }
        public int PlayerId { get; set; }
        public byte UniverseId { get; set; }
    }
}
