//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaslowJax_dbsEntities : DbContext
    {
        public MaslowJax_dbsEntities()
            : base("name=MaslowJax_dbsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Alliance> Alliances { get; set; }
        public DbSet<AllianceCandidate> AllianceCandidates { get; set; }
        public DbSet<CombatUnit> CombatUnits { get; set; }
        public DbSet<Espionage> Espionages { get; set; }
        public DbSet<EspionageAccess> EspionageAccesses { get; set; }
        public DbSet<EspionageBuilding> EspionageBuildings { get; set; }
        public DbSet<EspionageReport> EspionageReports { get; set; }
        public DbSet<EspionageT> EspionageTs { get; set; }
        public DbSet<ExplorerUser> ExplorerUsers { get; set; }
        public DbSet<ExplorerUser_Alliance> ExplorerUser_Alliance { get; set; }
        public DbSet<ExplorerUser_Player> ExplorerUser_Player { get; set; }
        public DbSet<GameSystem> GameSystems { get; set; }
        public DbSet<OpenId> OpenIds { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<Player> Players { get; set; }
        public DbSet<PlayerComment> PlayerComments { get; set; }
        public DbSet<PlayerHistory> PlayerHistories { get; set; }
        public DbSet<Position> Positions { get; set; }
        public DbSet<PositionSnapshot> PositionSnapshots { get; set; }
        public DbSet<Registration> Registrations { get; set; }
        public DbSet<ReportShip> ReportShips { get; set; }
        public DbSet<SnapshotAccess> SnapshotAccesses { get; set; }
        public DbSet<SfcSystem> SfcSystems { get; set; }
        public DbSet<Universe> Universes { get; set; }
        public DbSet<UserAlliance> UserAlliances { get; set; }
    }
}
