//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Rank { get; set; }
        public string Status { get; set; }
        public Nullable<int> AllianceId { get; set; }
        public System.DateTime Added { get; set; }
        public System.DateTime Updated { get; set; }
        public Nullable<bool> IsExtreme { get; set; }
        public Nullable<byte> UniverseId { get; set; }
    }
}
