//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SnapshotAccess
    {
        public int GrantedUserId { get; set; }
        public int PositionSnapshotId { get; set; }
        public System.DateTime PositionSnapshotDate { get; set; }
        public Nullable<System.DateTime> GrantedDate { get; set; }
        public Nullable<int> GrantedBy { get; set; }
        public Nullable<System.DateTime> PositionSnapshotUpdated { get; set; }
    }
}
