//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Universe
    {
        public Universe()
        {
            this.Alliances = new HashSet<Alliance>();
        }
    
        public byte UniverseId { get; set; }
        public string ShortName { get; set; }
        public string LongName { get; set; }
        public string HtmlMap { get; set; }
    
        public virtual ICollection<Alliance> Alliances { get; set; }
    }
}
