//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAlliance
    {
        public System.Guid UserGuid { get; set; }
        public Nullable<int> AllianceId { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<bool> Officer { get; set; }
        public Nullable<System.Guid> Token { get; set; }
    }
}
